version: "3"
services:
  mysql:
    build: ./requirements/mariadb
    volumes:
        - home/ehautefa/data:/var/lib/mysql
    environment: 
      MYSQL_ROOT_PASSWORD: pass
      MYSQL_DATABASE: wordpress
      MYSQL_USER: ehautefa
      MYSQL_PASSWORD: pass2
    restart: always

    