version: "3"
services:
  mysql:
    build: ./requirements/mariadb
    container_name: MariaDB
    restart: unless-stopped
    env_file: .env
    volumes:
        - ./home/ehautefa/data/mysql:/var/lib/mysql
    environment: 
      MYSQL_DATABASE: wordpress
    networks:
      - app-network
    stdin_open: true
    tty: true 
  wordpress:
    depends_on: 
      - mysql
    build: ./requirements/wordpress
    container_name: wordpress
    restart: unless-stopped
    env_file: .env
    environment: 
      - WORDPRESS_DB_HOST=db:3306
      - WORDPRESS_DB_USER=$MYSQL_USER
      - WORDPRESS_DB_PASSWORD=$MYSQL_PASSWORD
      - WORDPRESS_DB_NAME=wordpress
    volumes:
      - ./home/ehautefa/data/wordpress:/var/www/html
    networks: 
      - app-network
  webserver:
    depends_on: 
      - wordpress
    build: ./requirements/nginx
    container_name: nginx
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./home/ehautefa/data/wordpress:/var/www/html
      - ./requirements/nginx/conf/conf.d:/etc/nginx/conf.d
    networks:
      - app-network

volumes:
  wordpress:
  dbdata:

networks:
  app-network:
    driver: bridge
    