version: "3"
services:
  mariadb:
    build: ./requirements/mariadb
    restart: always
    env_file: .env
    volumes:
        - db-data:/var/lib/mysql/
    environment: 
      MYSQL_DATABASE: wordpress
    networks:
      - inception

  wordpress:
    depends_on: 
      - mariadb
    build: ./requirements/wordpress
    env_file: .env
    environment: 
      - WORDPRESS_DB_HOST=mysql:3306
      - WORDPRESS_DB_USER=$MYSQL_USER
      - WORDPRESS_DB_PASSWORD=$MYSQL_PASSWORD
      - WORDPRESS_DB_NAME=wordpress
    volumes:
      - /srcs:/srcs
      - db-data:/var/lib/mysql/
    networks:
      - inception
    
  nginx:
    depends_on: 
      - wordpress
    build: ./requirements/nginx
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - /srcs:/srcs
    networks:
      - inception 

volumes:
  db-data:

networks:
  inception:
    driver: bridge