version: "3"
services:
  mariadb:
    build: ./requirements/mariadb
    container_name: mariadb
    restart: always
    env_file: .env
    volumes:
        - db-data:/var/lib/mysql/
    environment: 
      MYSQL_DATABASE: wordpress
    networks:
      - inception

  wordpress:
    depends_on: 
      - mariadb
    container_name: wordpress
    build: ./requirements/wordpress
    env_file: .env
    environment: 
      - WORDPRESS_DB_HOST=mariadb:3306
      - WORDPRESS_DB_USER=$MYSQL_USER
      - WORDPRESS_DB_PASSWORD=$MYSQL_PASSWORD
      - WORDPRESS_DB_NAME=wordpress
    volumes:
      - wp-data:/srcs
      - db-data:/var/lib/mysql/
    networks:
      - inception
    
  nginx:
    depends_on: 
      - wordpress
    build: ./requirements/nginx
    container_name: nginx
    restart: unless-stopped
    ports:
      - "443:443"
    volumes:
      - wp-data:/srcs
    networks:
      - inception 

volumes:
  wp-data:
      driver: local
      driver_opts:
          type: 'none'
          o: 'bind'
          device: '${HOME}/data/wordpress'
  db-data:
      driver: local
      driver_opts:
          type: 'none'
          o: 'bind'
          device: '${HOME}/data/mysql'

networks:
  inception:
    driver: bridge