version: "3"
services:
  mysql:
    build: ./requirements/mariadb
    container_name: mariadb
    restart: always
    env_file: .env
    volumes:
        - db-data:/var/lib/mysql
    environment: 
      MYSQL_DATABASE: wordpress
    networks:
      - inception
      
  wordpress:
    depends_on: 
      - mysql
    build: ./requirements/wordpress
    container_name: wordpress
    restart: unless-stopped
    env_file: .env
    environment: 
      - WORDPRESS_DB_HOST=mysql:3306
      - WORDPRESS_DB_USER=$MYSQL_USER
      - WORDPRESS_DB_PASSWORD=$MYSQL_PASSWORD
      - WORDPRESS_DB_NAME=wordpress
    volumes:
      - wp-data:/var/www/html
      - db-data:/var/lib/mysql
    networks:
      - inception

  webserver:
    depends_on: 
      - wordpress
    build: ./requirements/nginx
    container_name: nginx
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - wp-data:/var/www/html
    networks:
      - inception


volumes:
  db-data:
  wp-data:

networks:
  inception:
    driver: bridge